<?php
	extract($_GET);
	require_once('../ajax/conn.php');
?>
<div id="content-header">
    <div id="breadcrumb"> <a><i class="icon-th-large"></i> Laporan > Laporan Prestasi > Laporan Prestasi Anggota Detail</a></div>
</div>
<div class="row-fluid">
&nbsp;
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon"><i class="icon-list"></i></span>
				<h5>Data Anggota</h5>
			</div>

			<div class="widget-content"> 
				<form class="form-horizontal font10" id="lab_filter"> 
				<?php 
					$q = $conn->query("
						SELECT m.* , ta.tipe_anggota, u.nama_unit
						FROM ytds_member m
						LEFT JOIN ytds_tipe_anggota ta
						on m.id_tipe_anggota = ta.id
						left join ytds_unit u
						on u.id = m.id_sekolah
						WHERE m.id = '$id' 
					")->fetch_assoc();
					
				?>
					<input value="<?=$q['nama_lengkap']?>" readonly name="nama_anggota" required id="laps_nama_anggota" placeholder="Nama Anggota" type="text" class="span3">	
					<input readonly name="id" required id="laps_id" placeholder="ID Anggota" type="hidden" class="span3">	
					<input value="<?=$q['tipe_anggota']?>" readonly name="class_prestasi" readonly id="laps_cp" placeholder="Kelas Prestasi" type="text" class="span3">	
					<input value="<?=$q['nama_unit']?>" readonly name="unit" readonly id="laps_unit" placeholder="Unit" type="text" class="span3">	
					
				</form>
			</div>
		</div>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon"><i class="icon-th"></i></span>
				<h5>Data Prestasi</h5>
			</div>

			<div class="widget-content">
			
				<!--button hidden id="laps_btnnew" class="btn btn-warning"><i class="icon-plus-sign"></i> Tambah Data </button-->
				<table id="lapsd_tbl" class="table table-responsive nowrap font12">
					<thead>
						<th> No. </th>
						<th> Tipe Event </th>
						<th> Kategori </th>
						<th> Event </th>
						<th> Medali </th>
						<th> Poin </th>
					</thead>
					<tbody id="tebodi_lapsd_tbl">
					<?php
					$query = $conn->query("
						SELECT pa.* , e.kategori, e.golongan,e.id_tipe_event
						FROM ytds_prestasi_anggota pa
						LEFT JOIN ytds_point_event e
						on e.id = pa.id_event
						WHERE id_member = '$id'
					");
					$i = 1;$tot = 0;
					while($r = $query->fetch_assoc()){
						echo "<tr>";
						echo "<td>".$i."</td>";$i++;
						echo "<td>".$r['id_tipe_event']."</td>";
						echo "<td>".$r['kategori']."</td>";
						echo "<td>".$r['event_name']."</td>";
						if($r['hasil']=='3')
							echo "<td>".'Juara 1</td>';
						else if($r['hasil']=='2')
							echo "<td>".'Juara 2</td>';
						else echo "<td>".'Juara 3</td>';
						echo "<td>".$r['point']."</td>"; $tot += $r['point'];
						echo "</tr>";
					}
					echo "
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td><b>Total Point</b></td>
							<td>$tot</td>
						</tr>
					";
					?>
					</tbody>
				</table>
			</div>

		</div>
	</div>
</div>
<script>

	if($(".visible-phone").css('display')=='block'){
		$("#nav_mobile_title").click();
	}
	$("#lapsd_tbl").DataTable({
		"pageLength": 150,
		"ordering":false,
		"dom": 'B',
		"buttons": [
			'copyHtml5',
			{
				extend:'excelHtml5',
				exportOptions:{
					columns: [ 0, 1, 2,3,4,5 ]
				},
				 messageTop: 'Data Prestasi Anggota <?=$q['nama_anggota']?>',
				 messageBottom: 'Generated by YTDS '
			},
			'csvHtml5',
			'pdfHtml5'
			
		]
	});
</script>