<div id="content-header">
    <div id="breadcrumb"> <a><i class="icon-th-large"></i> Laporan > Laporan Prestasi</a></div>
</div>
<div class="row-fluid">
	&nbsp;
</div>
<div class="row-fluid">
	<div class="span6">
		<button onclick="$('#menu_lap').click();loadView('v_laporan_prestasi_siswa.php');" class="btn btn-warning"><i class="icon-list"></i> Data Prestasi Anggota</button>
	</div>
</div>
<div class="row-fluid">
    <div class="span6">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon"><i class="icon-th"></i></span>
				<h5>Peringkat Kyorugi</h5>
			</div>
			<div class="widget-content">
				<table id="lap_tblk" class="table   responsive nowrap  font12" style="width:100%;">
					<thead>
						<tr>
						  <th>Rank</th>
						  <th>ID TGT</th> 
						  <th>Nama Lengkap</th>
						  <th>Unit</th> 
						  <th>Total Point</th>
						  <th>Detail</th>
						</tr>
					</thead>
					<tbody>
						<?php 
							require_once '../ajax/conn.php';
							
							$q1 = $conn->query("
								SELECT m.id,m.id_ytc,m.nama_lengkap, u.nama_unit, sum(pa.point) as total_pts
								FROM ytds_prestasi_anggota pa
								LEFT JOIN ytds_member m
								on m.id = pa.id_member
								LEFT JOIN ytds_unit u
								on u.id = m.id_sekolah
								where m.id_tipe_anggota = '5'
								group by m.id
								ORDER BY total_pts
							");
							$i1 = 1;
							while($r1 = $q1->fetch_assoc()){
								echo "<tr>";
								echo "<td>".$i1."</td>";$i1++;
								echo "<td>".$r1['id_ytc']."</td>";
								echo "<td>".$r1['nama_lengkap']."</td>";
								echo "<td>".$r1['nama_unit']."</td>";
								echo "<td>".$r1['total_pts']."</td>";
								echo "<td><a onclick='loadView(\"v_laporan_prestasi_detail.php?id=".$r1['id']."\");return false;'> >> </a></td>";
								echo "</tr>";
							}
						?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
    <div class="span6">
		<div class="widget-box">
			<div class="widget-title">
				<span class="icon"><i class="icon-th"></i></span>
				<h5>Peringkat Poomsae</h5>
			</div>
			<div class="widget-content">
				<table id="lap_tblp" class="table   responsive nowrap  font12" style="width:100%;">
					<thead>
						<tr>
						  <th>Rank</th>
						  <th>ID TGT</th> 
						  <th>Nama Lengkap</th>
						  <th>Unit</th> 
						  <th>Total Point</th>
						  <th>Detail</th>
						</tr>
					</thead>
					<tbody>
						<?php 
							$q2 = $conn->query("
								SELECT m.id,m.id_ytc,m.nama_lengkap, u.nama_unit, sum(pa.point) as total_pts
								FROM ytds_prestasi_anggota pa
								LEFT JOIN ytds_member m
								on m.id = pa.id_member
								LEFT JOIN ytds_unit u
								on u.id = m.id_sekolah
								where m.id_tipe_anggota = '4'
								group by m.id
								ORDER BY total_pts
							");
							$i2 = 1;
							while($r2 = $q2->fetch_assoc()){
								echo "<tr>";
								echo "<td>".$i2."</td>";$i1++;
								echo "<td>".$r2['id_ytc']."</td>";
								echo "<td>".$r2['nama_lengkap']."</td>";
								echo "<td>".$r2['nama_unit']."</td>";
								echo "<td>".$r2['total_pts']."</td>";
								echo "<td><a onclick='loadView(\"v_laporan_prestasi_detail.php?id=".$r2['id']."\");return false;'> >> </a></td>";
								echo "</tr>";
							}
						?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<script>
	$("#lap_tblk, #lap_tblp").dataTable({
		"pageLength": 150,
		"ordering":false,
		"dom": 'Bfrt',
		"buttons": [
			'copyHtml5',
			{
				extend:'excelHtml5',
				exportOptions:{
					columns: [ 0, 1, 2,3,4]
				},
				 messageTop: 'Peringkat Prestasi Berdasarkan Total Poin',
				 messageBottom: 'Generated by YTDS '
			},
			'csvHtml5',
			'pdfHtml5'
			
		]
	});
</script>